services:
  - type: web
    name: signbridge
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGODB_URI
        fromService:
          name: signbridge
          property: MONGODB_URI
      - key: FLASK_ENV
        value: production
